// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// exp_polynomial_cpp
Rcpp::NumericVector exp_polynomial_cpp(Rcpp::NumericVector x_vec, Rcpp::NumericVector params);
RcppExport SEXP _eqR_exp_polynomial_cpp(SEXP x_vecSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_polynomial_cpp(x_vec, params));
    return rcpp_result_gen;
END_RCPP
}
// biv_exp_polynomial_vec_cpp
Rcpp::NumericVector biv_exp_polynomial_vec_cpp(Rcpp::NumericVector x_vec, Rcpp::NumericVector y_vec, Rcpp::NumericVector bivar_params, Rcpp::IntegerVector x_powers, Rcpp::IntegerVector y_powers);
RcppExport SEXP _eqR_biv_exp_polynomial_vec_cpp(SEXP x_vecSEXP, SEXP y_vecSEXP, SEXP bivar_paramsSEXP, SEXP x_powersSEXP, SEXP y_powersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bivar_params(bivar_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x_powers(x_powersSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_powers(y_powersSEXP);
    rcpp_result_gen = Rcpp::wrap(biv_exp_polynomial_vec_cpp(x_vec, y_vec, bivar_params, x_powers, y_powers));
    return rcpp_result_gen;
END_RCPP
}
// integrand_fully_vectorized_cpp
Rcpp::NumericMatrix integrand_fully_vectorized_cpp(Rcpp::NumericVector x, Rcpp::NumericVector y_nodes, Rcpp::NumericVector bivar_params, Rcpp::IntegerVector x_powers, Rcpp::IntegerVector y_powers);
RcppExport SEXP _eqR_integrand_fully_vectorized_cpp(SEXP xSEXP, SEXP y_nodesSEXP, SEXP bivar_paramsSEXP, SEXP x_powersSEXP, SEXP y_powersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_nodes(y_nodesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bivar_params(bivar_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x_powers(x_powersSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_powers(y_powersSEXP);
    rcpp_result_gen = Rcpp::wrap(integrand_fully_vectorized_cpp(x, y_nodes, bivar_params, x_powers, y_powers));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eqR_exp_polynomial_cpp", (DL_FUNC) &_eqR_exp_polynomial_cpp, 2},
    {"_eqR_biv_exp_polynomial_vec_cpp", (DL_FUNC) &_eqR_biv_exp_polynomial_vec_cpp, 5},
    {"_eqR_integrand_fully_vectorized_cpp", (DL_FUNC) &_eqR_integrand_fully_vectorized_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_eqR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
