# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate the Exponential of a Polynomial (Vectorized C++ Version)
NULL

#' Bivariate Exponential Polynomial (Vectorized C++ Version)
NULL

#' Integrand for Marginal CDF Calculation (C++ Version)
NULL

exp_polynomial_cpp <- function(x_vec, params) {
    .Call(`_eqR_exp_polynomial_cpp`, x_vec, params)
}

biv_exp_polynomial_vec_cpp <- function(x_vec, y_vec, bivar_params, x_powers, y_powers) {
    .Call(`_eqR_biv_exp_polynomial_vec_cpp`, x_vec, y_vec, bivar_params, x_powers, y_powers)
}

integrand_fully_vectorized_cpp <- function(x, y_nodes, bivar_params, x_powers, y_powers) {
    .Call(`_eqR_integrand_fully_vectorized_cpp`, x, y_nodes, bivar_params, x_powers, y_powers)
}

